runtime: python312

entrypoint: gunicorn --bind :$PORT problematy.wsgi:application

env_variables:
    APPENGINE_URL: https://animated-backup-427810-r5.uc.r.appspot.com
    SECRET_KEY: "asdasasdasdasd"
    DB_NAME: "problematydb"
    DB_USER: "uproblematy"
    DB_PASSWORD: "ACTvjzDyAsyS4fl3"
    DB_HOST: "/cloudsql/animated-backup-427810-r5:us-central1:problematy"
    DB_PORT: "5432"

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto