on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  deploy:
    environment: ${{ inputs.environment }}
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
  #TODO: this section should be replaced with another solution (probably separate javascript form python)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.14'
    - name: Install dependencies
      run: npm install
      working-directory: ./frontend
    - name: Build javascript
      run: npm run build
      working-directory: ./frontend
    - name: Remove frontend dir # for fronted built bundle is used
      run: rm -rf ./frontend
  # end of TODO
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        access_token_lifetime: '300s'
    - name: Prepare config
      run : |
        echo '${{ secrets.CONFIG }}' >config.yml
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Prepare dependencies
      run : |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
        poetry install
        poetry run pybabel compile -d translations
        poetry export -f requirements.txt --output requirements.txt --without-hashes
    - id: deploy
      uses: google-github-actions/deploy-appengine@v0
      with:
        deliverables: app.${{ inputs.environment }}.yaml
        version: ${{ inputs.environment }}
        promote: ${{ inputs.environment == 'production' }}
    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"
