name: E2E tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'examples/**/*.json'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'examples/**/*.json'

# Cancel outdated workflow runs when new commits are pushed to the PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    permissions:
      contents: read
      actions: read
      pull-requests: write
    uses: problematy/goodmap-e2e-tests/.github/workflows/e2e-tests.yml@cac4085419b27dfa74062cab5f2f2fcc43ffa230
    with:
      goodmap-version: ${{ github.sha }}
      goodmap-frontend-version: ${{ github.sha }}
