name: Good map

on:
  push

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.14'
    - name: Install dependencies
      run: npm install
    - name: Test with jest
      run: npm test

  deploy:
    needs: [backend-test, frontend-test]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: production
