name: Good map

on:
  push

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest

  deploy:
    needs: build
    environment: goodmap_env
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        access_token_lifetime: '300s'
    - id: deploy
      uses: google-github-actions/deploy-appengine@v0
    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"
