name: Testing pipeline

on:
  push

permissions:
  contents: 'read'

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Test with pytest
      run: |
        poetry run coverage run -m pytest
        poetry run coverage lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: "./coverage.lcov"
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run app in background (prepare for e2e test)
      run: poetry FLASK_APP="goodmap.goodmap:create_app(config_path='./tests/e2e_tests/config.yml')" flask run &
    - name: Install and run cypress tests
      working-directory: "./tests/e2e_tests"
      run: |
        npm install cypress
        node_modules/cypress/bin/cypress run
