name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  publish:
    runs-on: ubuntu-latest
    needs: tests
    environment:
      name: pypi
      url: https://pypi.org/p/goodmap
    steps:
      - name: Generate bot app token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.MY_RELEASER_ID }}
          private-key: ${{ secrets.MY_RELEASER_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --without local

      - name: Run semantic release version
        id: release
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --global user.name "semantic-release"
          git config --global user.email "semantic-release@users.noreply.github.com"
          poetry run semantic-release version
          if [ -n "$(ls -A dist/ 2>/dev/null)" ]; then
            echo "new_release=true" >> $GITHUB_OUTPUT
          else
            echo "new_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish semantic release
        if: steps.release.outputs.new_release == 'true'
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: poetry run semantic-release publish

      - name: Publish to PyPI
        if: steps.release.outputs.new_release == 'true'
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
        with:
          packages-dir: dist/
