name: Release to pypi

on:
  push:
    tags:
      - '*.*.*'
    branches:
      - release-test
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry version $(git describe --tags --abbrev=0)
        poetry build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        #verify_metadata: false
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Update CHANGELOG
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        tag: ${{ github.ref_name }}

    - name: Release python package
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
        tag_name: ${{ github.ref }}
        body: |
          ${{ github.event.release.body }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
