name: Release to pypi

on:
  release:
    types: [published]


permissions:
  contents: 'read'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'  # TODO remove this line after the submodules are removed
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        #verify_metadata: false
        password: ${{ secrets.PYPI_API_TOKEN }}
